### ISSUE TITLE
React 15 = :(

### ISSUE THREAD

**Issue by Trevoke** [bebraw/react-ellipsify#9]
Can't be installed with React 15 because the peer dependency says React < 1.0.0 ...

**Comment by bebraw** [comment]
Thanks! This should be fixed in `0.6.1`.

**Comment by Trevoke** [comment]
It occurred to me _just now_ that I could have opened a PR to fix it, and I apologize for not having done that.

Thank you for your prompt fix, as it saves me further hours of pain.

**Comment by bebraw** [comment]
It's alright. The changes weren't entirely easy so better this way. 👍
